owner: bdeak4
repo: uptime

sites:
  - name: chatter
    url: https://chatter.bdeak.net
  - name: bdeak.net
    url: https://bdeak.net
  - name: ludo
    url: https://ludo.bdeak.net
  - name: postsandcomments
    url: https://postsandcomments.bdeak.net
  - name: menze
    url: https://menze.bdeak.net

status-website:
  cname: uptime.bdeak.net
  name: uptime
  introTitle: uptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
